version: '3'

services:
  php:
      build:
        context: .
        dockerfile: ./docker/php/Dockerfile
        args:
          CONTAINER_USER_ID: '${CONTAINER_USER_ID}'
          CONTAINER_GROUP_ID: '${CONTAINER_GROUP_ID}'
          CONTAINER_USER_NAME: '${CONTAINER_USER_NAME}'
          CONTAINER_GROUP_NAME: '${CONTAINER_GROUP_NAME}'
      volumes:
        - ./:/var/www/html
      ports:
        - 80:80
        - 443:443
        - 8887:8887
        - 24678:24678
      environment:
        CONTAINER_USER_ID: '${CONTAINER_USER_ID}'
        CONTAINER_GROUP_ID: '${CONTAINER_GROUP_ID}'
        CONTAINER_USER_NAME: '${CONTAINER_USER_NAME}'
        CONTAINER_GROUP_NAME: '${CONTAINER_GROUP_NAME}'
        APACHE_RUN_USER: '${CONTAINER_USER_NAME}'
        APACHE_RUN_GROUP: '${CONTAINER_GROUP_NAME}'
      user: ${CONTAINER_USER_ID}:${CONTAINER_GROUP_ID}
      container_name: ${CONTAINER_NAME_PHP}
  mysql:
      build:
        context: .
        dockerfile: ./docker/mysql/Dockerfile
      volumes:
        - ./docker/mysql/etc/my.cnf:/etc/mysql/conf.d/my.cnf
      ports:
        - 3306:3306
      command: --innodb-use-native-aio=0
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=cloud_note
        - MYSQL_USER=docker
        - MYSQL_PASSWORD=docker
      container_name: ${CONTAINER_NAME_MYSQL}
