name: CI
on:
  push:
    branches: [ "develop" ]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: npm ci
        run: npm ci
        working-directory: ./nuxt3

      - name: ESLint
        run: npm run lint
        working-directory: ./nuxt3
