name: CI
on:
  push:
    branches: [ "develop" ]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: ./docker/php
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: docker/build-push-action@v4
        with:
          context: ./docker/mysql
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: setUp .env
        run: cp .env.ci.example .env

      - name: setUp Docker
        run: docker compose up -d --wait

      - name: container info
        run: docker-compose ps

      - name: SetUp App
        run: make build

      - name: Create admin user
        run: make create_admin_user

      - name: ESLint
        run: make lint

      - name: PHPCS
        run: make phpcs

      - name: Backend test
        run: make test
