name: CI
on:
  push:
    branches: [ "develop" ]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setUp .env
        run: cp .env.ci.example .env

      - name: setUp Docker
        run: docker compose up -d --wait

      - name: SetUp App
        run: make build

      - name: Create admin user
        run: make create_admin_user

      - name: ESLint
        run: make lint

      - name: Check TypeScript
        run: make tsc

      - name: Check Vue-TypeScript
        run: make vue-tsc

      - name: PHPCS
        run: make phpcs

      - name: Backend test
        run: make test
