name: CI
on:
  push:
    branches: [ "develop" ]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setUp Docker
        run: make up

      - name: SetUp App
        run: make build && make create_admin_user

      - name: ESLint
        run: make lint

      - name: PHPCS
        run: make phpcs
